import React, {Component} from 'react';
import Result from './result';

class ResultsContainer extends Component{
    render(){
        return(
            <div style={{display:'flex',flexDirection:'row',flexWrap:'wrap',overflowY:'auto',height:'40vh',width:'100%'}}>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
                <Result/>
            </div>
        );
    }
}

export default ResultsContainer;